CREATE TYPE "public"."advising_kind" AS ENUM('recurring', 'extra');--> statement-breakpoint
CREATE TYPE "public"."advising_modality" AS ENUM('classroom', 'virtual', 'hybrid');--> statement-breakpoint
CREATE TYPE "public"."alert_type" AS ENUM('academic_risk', 'high_load');--> statement-breakpoint
CREATE TYPE "public"."course_category" AS ENUM('general_studies', 'common', 'faculty', 'elective');--> statement-breakpoint
CREATE TYPE "public"."curriculum_simulation_status" AS ENUM('planned', 'simulated_completed');--> statement-breakpoint
CREATE TYPE "public"."enrollment_status" AS ENUM('active', 'withdrawn', 'completed');--> statement-breakpoint
CREATE TYPE "public"."prerequisite_type" AS ENUM('course', 'completed_cycle');--> statement-breakpoint
CREATE TYPE "public"."representative_position" AS ENUM('delegate', 'subdelegate');--> statement-breakpoint
CREATE TYPE "public"."student_course_status" AS ENUM('in_progress', 'approved', 'failed', 'withdrawn');--> statement-breakpoint
CREATE TYPE "public"."student_specialty_type" AS ENUM('primary', 'interest');--> statement-breakpoint
CREATE TABLE "academic_period" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "academic_period_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"code" varchar(20) NOT NULL,
	"start_date" date NOT NULL,
	"end_date" date NOT NULL,
	"is_active" boolean DEFAULT true NOT NULL,
	CONSTRAINT "academic_period_code_unique" UNIQUE("code"),
	CONSTRAINT "chk_academic_period_dates" CHECK ("academic_period"."start_date" < "academic_period"."end_date")
);
--> statement-breakpoint
CREATE TABLE "academic_week" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "academic_week_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"academic_period_id" integer NOT NULL,
	"week_number" integer NOT NULL,
	"start_date" date NOT NULL,
	"end_date" date NOT NULL,
	CONSTRAINT "uq_academic_week_period_number" UNIQUE("academic_period_id","week_number"),
	CONSTRAINT "chk_academic_week_number" CHECK ("academic_week"."week_number" > 0),
	CONSTRAINT "chk_academic_week_dates" CHECK ("academic_week"."start_date" <= "academic_week"."end_date")
);
--> statement-breakpoint
CREATE TABLE "advising_rsvp" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "advising_rsvp_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"advising_session_id" integer NOT NULL,
	"student_id" integer NOT NULL,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	CONSTRAINT "uq_advising_rsvp" UNIQUE("advising_session_id","student_id")
);
--> statement-breakpoint
CREATE TABLE "alert" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "alert_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"student_id" integer NOT NULL,
	"type" "alert_type" NOT NULL,
	"title" varchar(150) NOT NULL,
	"message" text NOT NULL,
	"is_read" boolean DEFAULT false NOT NULL,
	"created_at" timestamp DEFAULT now() NOT NULL
);
--> statement-breakpoint
CREATE TABLE "announcement" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "announcement_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"section_representative_id" integer NOT NULL,
	"title" varchar(150) NOT NULL,
	"message" text NOT NULL,
	"published_at" timestamp DEFAULT now() NOT NULL,
	"is_active" boolean DEFAULT true NOT NULL
);
--> statement-breakpoint
CREATE TABLE "app_user" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "app_user_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"code" varchar(30) NOT NULL,
	"full_name" varchar(150) NOT NULL,
	"institutional_email" varchar(150) NOT NULL,
	"password_hash" varchar(255) NOT NULL,
	"google_id" varchar(255),
	"token_version" integer DEFAULT 1 NOT NULL,
	CONSTRAINT "app_user_code_unique" UNIQUE("code"),
	CONSTRAINT "app_user_institutional_email_unique" UNIQUE("institutional_email")
);
--> statement-breakpoint
CREATE TABLE "assessment" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "assessment_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"syllabus_id" integer NOT NULL,
	"assessment_type_id" integer NOT NULL,
	"code" varchar(30) NOT NULL,
	"name" varchar(150) NOT NULL,
	"week_number" integer NOT NULL,
	"weight" numeric(5, 2) NOT NULL,
	CONSTRAINT "uq_assessment_syllabus_code" UNIQUE("syllabus_id","code"),
	CONSTRAINT "chk_assessment_week_number" CHECK ("assessment"."week_number" > 0),
	CONSTRAINT "chk_assessment_weight" CHECK ("assessment"."weight" > 0 AND "assessment"."weight" <= 100)
);
--> statement-breakpoint
CREATE TABLE "assessment_type" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "assessment_type_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"name" varchar(120) NOT NULL,
	"abbreviation" varchar(30),
	"description" text,
	CONSTRAINT "assessment_type_name_unique" UNIQUE("name")
);
--> statement-breakpoint
CREATE TABLE "career" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "career_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"code" varchar(30) NOT NULL,
	"name" varchar(120) NOT NULL,
	"faculty" varchar(120) NOT NULL,
	CONSTRAINT "career_code_unique" UNIQUE("code")
);
--> statement-breakpoint
CREATE TABLE "course" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "course_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"code" varchar(30) NOT NULL,
	"name" varchar(150) NOT NULL,
	"default_credit" integer NOT NULL,
	"origin_faculty" varchar(120),
	CONSTRAINT "course_code_unique" UNIQUE("code"),
	CONSTRAINT "chk_course_default_credit" CHECK ("course"."default_credit" > 0)
);
--> statement-breakpoint
CREATE TABLE "course_advising_session" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "course_advising_session_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"course_offering_id" integer NOT NULL,
	"section_id" integer,
	"teacher_id" integer NOT NULL,
	"day_of_week" integer NOT NULL,
	"start_time" time NOT NULL,
	"end_time" time NOT NULL,
	"classroom" varchar(100),
	"meeting_url" varchar(255),
	"modality" "advising_modality" DEFAULT 'hybrid' NOT NULL,
	"note" text,
	"kind" "advising_kind" DEFAULT 'recurring' NOT NULL,
	"session_date" date,
	"capacity" integer,
	CONSTRAINT "chk_course_advising_day" CHECK ("course_advising_session"."day_of_week" BETWEEN 1 AND 7),
	CONSTRAINT "chk_course_advising_time" CHECK ("course_advising_session"."start_time" < "course_advising_session"."end_time"),
	CONSTRAINT "chk_course_advising_extra_date" CHECK ("course_advising_session"."kind" <> 'extra' OR "course_advising_session"."session_date" IS NOT NULL),
	CONSTRAINT "chk_course_advising_capacity" CHECK ("course_advising_session"."capacity" IS NULL OR "course_advising_session"."capacity" > 0)
);
--> statement-breakpoint
CREATE TABLE "course_offering" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "course_offering_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"academic_period_id" integer NOT NULL,
	"course_id" integer NOT NULL,
	CONSTRAINT "uq_course_offering" UNIQUE("academic_period_id","course_id")
);
--> statement-breakpoint
CREATE TABLE "course_prerequisite" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "course_prerequisite_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"curriculum_id" integer NOT NULL,
	"curriculum_course_id" integer NOT NULL,
	"prerequisite_type" "prerequisite_type" NOT NULL,
	"prerequisite_curriculum_course_id" integer,
	"required_cycle" integer,
	CONSTRAINT "chk_course_prerequisite_kind" CHECK (
    ("course_prerequisite"."prerequisite_type" = 'course' AND "course_prerequisite"."prerequisite_curriculum_course_id" IS NOT NULL AND "course_prerequisite"."required_cycle" IS NULL)
    OR
    ("course_prerequisite"."prerequisite_type" = 'completed_cycle' AND "course_prerequisite"."prerequisite_curriculum_course_id" IS NULL AND "course_prerequisite"."required_cycle" IS NOT NULL)
  ),
	CONSTRAINT "chk_course_prerequisite_required_cycle" CHECK ("course_prerequisite"."required_cycle" IS NULL OR "course_prerequisite"."required_cycle" > 0),
	CONSTRAINT "chk_course_prerequisite_not_self" CHECK ("course_prerequisite"."prerequisite_curriculum_course_id" IS NULL OR "course_prerequisite"."curriculum_course_id" <> "course_prerequisite"."prerequisite_curriculum_course_id")
);
--> statement-breakpoint
CREATE TABLE "curriculum" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "curriculum_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"career_id" integer NOT NULL,
	"name" varchar(120) NOT NULL,
	CONSTRAINT "curriculum_career_id_unique" UNIQUE("career_id"),
	CONSTRAINT "uq_curriculum_id_career" UNIQUE("id","career_id")
);
--> statement-breakpoint
CREATE TABLE "curriculum_course" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "curriculum_course_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"curriculum_id" integer NOT NULL,
	"course_id" integer NOT NULL,
	"cycle" integer NOT NULL,
	"display_order" integer NOT NULL,
	"credit" integer NOT NULL,
	"category" "course_category" DEFAULT 'faculty' NOT NULL,
	CONSTRAINT "uq_curriculum_course" UNIQUE("curriculum_id","course_id"),
	CONSTRAINT "uq_curriculum_course_id_curriculum" UNIQUE("id","curriculum_id"),
	CONSTRAINT "chk_curriculum_course_cycle" CHECK ("curriculum_course"."cycle" > 0),
	CONSTRAINT "chk_curriculum_course_display_order" CHECK ("curriculum_course"."display_order" > 0),
	CONSTRAINT "chk_curriculum_course_credit" CHECK ("curriculum_course"."credit" > 0)
);
--> statement-breakpoint
CREATE TABLE "curriculum_course_specialty" (
	"curriculum_course_id" integer NOT NULL,
	"specialty_id" integer NOT NULL,
	CONSTRAINT "curriculum_course_specialty_curriculum_course_id_specialty_id_pk" PRIMARY KEY("curriculum_course_id","specialty_id")
);
--> statement-breakpoint
CREATE TABLE "enrollment" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "enrollment_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"student_id" integer NOT NULL,
	"section_id" integer NOT NULL,
	"status" "enrollment_status" DEFAULT 'active' NOT NULL,
	"attended_hours" numeric(5, 2) DEFAULT '0' NOT NULL,
	"absent_hours" numeric(5, 2) DEFAULT '0' NOT NULL,
	"total_hours" numeric(5, 2) DEFAULT '0' NOT NULL,
	CONSTRAINT "uq_enrollment_student_section" UNIQUE("student_id","section_id"),
	CONSTRAINT "uq_enrollment_id_section" UNIQUE("id","section_id"),
	CONSTRAINT "chk_enrollment_attended_hours" CHECK ("enrollment"."attended_hours" >= 0),
	CONSTRAINT "chk_enrollment_absent_hours" CHECK ("enrollment"."absent_hours" >= 0),
	CONSTRAINT "chk_enrollment_total_hours" CHECK ("enrollment"."total_hours" >= 0),
	CONSTRAINT "chk_enrollment_attendance_hours" CHECK ("enrollment"."attended_hours" + "enrollment"."absent_hours" <= "enrollment"."total_hours")
);
--> statement-breakpoint
CREATE TABLE "password_reset_token" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "password_reset_token_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"user_id" integer NOT NULL,
	"token_hash" varchar(64) NOT NULL,
	"expires_at" timestamp with time zone NOT NULL,
	"used_at" timestamp with time zone,
	"attempts" integer DEFAULT 0 NOT NULL,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL
);
--> statement-breakpoint
CREATE TABLE "schedule_session" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "schedule_session_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"section_id" integer NOT NULL,
	"day_of_week" integer NOT NULL,
	"start_time" time NOT NULL,
	"end_time" time NOT NULL,
	"classroom" varchar(100),
	"color_hex" varchar(20),
	CONSTRAINT "uq_schedule_session" UNIQUE("section_id","day_of_week","start_time"),
	CONSTRAINT "chk_schedule_session_day" CHECK ("schedule_session"."day_of_week" BETWEEN 1 AND 7),
	CONSTRAINT "chk_schedule_session_time" CHECK ("schedule_session"."start_time" < "schedule_session"."end_time")
);
--> statement-breakpoint
CREATE TABLE "section" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "section_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"course_offering_id" integer NOT NULL,
	"teacher_id" integer NOT NULL,
	"code" varchar(30) NOT NULL,
	"jp_id" integer,
	CONSTRAINT "uq_section_offering_code" UNIQUE("course_offering_id","code"),
	CONSTRAINT "uq_section_id_offering" UNIQUE("id","course_offering_id"),
	CONSTRAINT "chk_section_jp_not_teacher" CHECK ("section"."jp_id" IS NULL OR "section"."jp_id" <> "section"."teacher_id")
);
--> statement-breakpoint
CREATE TABLE "section_representative" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "section_representative_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"section_id" integer NOT NULL,
	"enrollment_id" integer NOT NULL,
	"position" "representative_position" NOT NULL,
	"is_active" boolean DEFAULT true NOT NULL,
	CONSTRAINT "section_representative_enrollment_id_unique" UNIQUE("enrollment_id")
);
--> statement-breakpoint
CREATE TABLE "specialty" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "specialty_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"career_id" integer NOT NULL,
	"name" varchar(120) NOT NULL,
	"description" text,
	"is_active" boolean DEFAULT true NOT NULL,
	CONSTRAINT "uq_specialty_career_name" UNIQUE("career_id","name")
);
--> statement-breakpoint
CREATE TABLE "student" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "student_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"user_id" integer NOT NULL,
	"career_id" integer NOT NULL,
	"curriculum_id" integer NOT NULL,
	"current_level" integer,
	"specialty_setup_completed" boolean DEFAULT false NOT NULL,
	CONSTRAINT "student_user_id_unique" UNIQUE("user_id"),
	CONSTRAINT "uq_student_id_career" UNIQUE("id","career_id"),
	CONSTRAINT "uq_student_id_curriculum" UNIQUE("id","curriculum_id"),
	CONSTRAINT "chk_student_current_level" CHECK ("student"."current_level" IS NULL OR "student"."current_level" BETWEEN 1 AND 10)
);
--> statement-breakpoint
CREATE TABLE "student_course_progress" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "student_course_progress_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"student_id" integer NOT NULL,
	"curriculum_id" integer NOT NULL,
	"curriculum_course_id" integer NOT NULL,
	"status" "student_course_status" NOT NULL,
	CONSTRAINT "uq_student_course_progress" UNIQUE("student_id","curriculum_course_id")
);
--> statement-breakpoint
CREATE TABLE "student_curriculum_simulation" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "student_curriculum_simulation_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"student_id" integer NOT NULL,
	"curriculum_id" integer NOT NULL,
	"curriculum_course_id" integer NOT NULL,
	"status" "curriculum_simulation_status" NOT NULL,
	CONSTRAINT "uq_student_curriculum_simulation" UNIQUE("student_id","curriculum_course_id")
);
--> statement-breakpoint
CREATE TABLE "student_score" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "student_score_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"enrollment_id" integer NOT NULL,
	"assessment_id" integer NOT NULL,
	"value" numeric(5, 2),
	CONSTRAINT "uq_student_score" UNIQUE("enrollment_id","assessment_id"),
	CONSTRAINT "chk_student_score_value" CHECK ("student_score"."value" IS NULL OR "student_score"."value" BETWEEN 0 AND 20)
);
--> statement-breakpoint
CREATE TABLE "student_specialty" (
	"student_id" integer NOT NULL,
	"specialty_id" integer NOT NULL,
	"selection_type" "student_specialty_type" DEFAULT 'interest' NOT NULL,
	"is_active" boolean DEFAULT true NOT NULL,
	CONSTRAINT "student_specialty_student_id_specialty_id_pk" PRIMARY KEY("student_id","specialty_id")
);
--> statement-breakpoint
CREATE TABLE "syllabus" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "syllabus_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"course_offering_id" integer NOT NULL,
	"title" varchar(150),
	"drive_file_id" varchar(120) NOT NULL,
	"drive_file_url" varchar(255) NOT NULL,
	CONSTRAINT "syllabus_drive_file_id_unique" UNIQUE("drive_file_id"),
	CONSTRAINT "uq_syllabus_course_offering" UNIQUE("course_offering_id")
);
--> statement-breakpoint
CREATE TABLE "teacher" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "teacher_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"teacher_code" varchar(50),
	"full_name" varchar(150) NOT NULL,
	"institutional_email" varchar(150),
	"user_id" integer,
	CONSTRAINT "teacher_teacher_code_unique" UNIQUE("teacher_code"),
	CONSTRAINT "teacher_institutional_email_unique" UNIQUE("institutional_email"),
	CONSTRAINT "teacher_user_id_unique" UNIQUE("user_id")
);
--> statement-breakpoint
ALTER TABLE "academic_week" ADD CONSTRAINT "academic_week_academic_period_id_academic_period_id_fk" FOREIGN KEY ("academic_period_id") REFERENCES "public"."academic_period"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "advising_rsvp" ADD CONSTRAINT "advising_rsvp_advising_session_id_course_advising_session_id_fk" FOREIGN KEY ("advising_session_id") REFERENCES "public"."course_advising_session"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "advising_rsvp" ADD CONSTRAINT "advising_rsvp_student_id_student_id_fk" FOREIGN KEY ("student_id") REFERENCES "public"."student"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "alert" ADD CONSTRAINT "alert_student_id_student_id_fk" FOREIGN KEY ("student_id") REFERENCES "public"."student"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "announcement" ADD CONSTRAINT "announcement_section_representative_id_section_representative_id_fk" FOREIGN KEY ("section_representative_id") REFERENCES "public"."section_representative"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "assessment" ADD CONSTRAINT "assessment_syllabus_id_syllabus_id_fk" FOREIGN KEY ("syllabus_id") REFERENCES "public"."syllabus"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "assessment" ADD CONSTRAINT "assessment_assessment_type_id_assessment_type_id_fk" FOREIGN KEY ("assessment_type_id") REFERENCES "public"."assessment_type"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "course_advising_session" ADD CONSTRAINT "course_advising_session_course_offering_id_course_offering_id_fk" FOREIGN KEY ("course_offering_id") REFERENCES "public"."course_offering"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "course_advising_session" ADD CONSTRAINT "course_advising_session_section_id_section_id_fk" FOREIGN KEY ("section_id") REFERENCES "public"."section"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "course_advising_session" ADD CONSTRAINT "course_advising_session_teacher_id_teacher_id_fk" FOREIGN KEY ("teacher_id") REFERENCES "public"."teacher"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "course_offering" ADD CONSTRAINT "course_offering_academic_period_id_academic_period_id_fk" FOREIGN KEY ("academic_period_id") REFERENCES "public"."academic_period"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "course_offering" ADD CONSTRAINT "course_offering_course_id_course_id_fk" FOREIGN KEY ("course_id") REFERENCES "public"."course"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "course_prerequisite" ADD CONSTRAINT "course_prerequisite_curriculum_id_curriculum_id_fk" FOREIGN KEY ("curriculum_id") REFERENCES "public"."curriculum"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "course_prerequisite" ADD CONSTRAINT "course_prerequisite_curriculum_course_id_curriculum_course_id_fk" FOREIGN KEY ("curriculum_course_id") REFERENCES "public"."curriculum_course"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "course_prerequisite" ADD CONSTRAINT "course_prerequisite_prerequisite_curriculum_course_id_curriculum_course_id_fk" FOREIGN KEY ("prerequisite_curriculum_course_id") REFERENCES "public"."curriculum_course"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "curriculum" ADD CONSTRAINT "curriculum_career_id_career_id_fk" FOREIGN KEY ("career_id") REFERENCES "public"."career"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "curriculum_course" ADD CONSTRAINT "curriculum_course_curriculum_id_curriculum_id_fk" FOREIGN KEY ("curriculum_id") REFERENCES "public"."curriculum"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "curriculum_course" ADD CONSTRAINT "curriculum_course_course_id_course_id_fk" FOREIGN KEY ("course_id") REFERENCES "public"."course"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "curriculum_course_specialty" ADD CONSTRAINT "curriculum_course_specialty_curriculum_course_id_curriculum_course_id_fk" FOREIGN KEY ("curriculum_course_id") REFERENCES "public"."curriculum_course"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "curriculum_course_specialty" ADD CONSTRAINT "curriculum_course_specialty_specialty_id_specialty_id_fk" FOREIGN KEY ("specialty_id") REFERENCES "public"."specialty"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "enrollment" ADD CONSTRAINT "enrollment_student_id_student_id_fk" FOREIGN KEY ("student_id") REFERENCES "public"."student"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "enrollment" ADD CONSTRAINT "enrollment_section_id_section_id_fk" FOREIGN KEY ("section_id") REFERENCES "public"."section"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "password_reset_token" ADD CONSTRAINT "password_reset_token_user_id_app_user_id_fk" FOREIGN KEY ("user_id") REFERENCES "public"."app_user"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "schedule_session" ADD CONSTRAINT "schedule_session_section_id_section_id_fk" FOREIGN KEY ("section_id") REFERENCES "public"."section"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "section" ADD CONSTRAINT "section_course_offering_id_course_offering_id_fk" FOREIGN KEY ("course_offering_id") REFERENCES "public"."course_offering"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "section" ADD CONSTRAINT "section_teacher_id_teacher_id_fk" FOREIGN KEY ("teacher_id") REFERENCES "public"."teacher"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "section" ADD CONSTRAINT "section_jp_id_teacher_id_fk" FOREIGN KEY ("jp_id") REFERENCES "public"."teacher"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "section_representative" ADD CONSTRAINT "section_representative_section_id_section_id_fk" FOREIGN KEY ("section_id") REFERENCES "public"."section"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "section_representative" ADD CONSTRAINT "section_representative_enrollment_id_enrollment_id_fk" FOREIGN KEY ("enrollment_id") REFERENCES "public"."enrollment"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "specialty" ADD CONSTRAINT "specialty_career_id_career_id_fk" FOREIGN KEY ("career_id") REFERENCES "public"."career"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "student" ADD CONSTRAINT "student_user_id_app_user_id_fk" FOREIGN KEY ("user_id") REFERENCES "public"."app_user"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "student_course_progress" ADD CONSTRAINT "student_course_progress_student_id_student_id_fk" FOREIGN KEY ("student_id") REFERENCES "public"."student"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "student_course_progress" ADD CONSTRAINT "student_course_progress_curriculum_id_curriculum_id_fk" FOREIGN KEY ("curriculum_id") REFERENCES "public"."curriculum"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "student_course_progress" ADD CONSTRAINT "student_course_progress_curriculum_course_id_curriculum_course_id_fk" FOREIGN KEY ("curriculum_course_id") REFERENCES "public"."curriculum_course"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "student_curriculum_simulation" ADD CONSTRAINT "student_curriculum_simulation_student_id_student_id_fk" FOREIGN KEY ("student_id") REFERENCES "public"."student"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "student_curriculum_simulation" ADD CONSTRAINT "student_curriculum_simulation_curriculum_id_curriculum_id_fk" FOREIGN KEY ("curriculum_id") REFERENCES "public"."curriculum"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "student_curriculum_simulation" ADD CONSTRAINT "student_curriculum_simulation_curriculum_course_id_curriculum_course_id_fk" FOREIGN KEY ("curriculum_course_id") REFERENCES "public"."curriculum_course"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "student_score" ADD CONSTRAINT "student_score_enrollment_id_enrollment_id_fk" FOREIGN KEY ("enrollment_id") REFERENCES "public"."enrollment"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "student_score" ADD CONSTRAINT "student_score_assessment_id_assessment_id_fk" FOREIGN KEY ("assessment_id") REFERENCES "public"."assessment"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "student_specialty" ADD CONSTRAINT "student_specialty_student_id_student_id_fk" FOREIGN KEY ("student_id") REFERENCES "public"."student"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "student_specialty" ADD CONSTRAINT "student_specialty_specialty_id_specialty_id_fk" FOREIGN KEY ("specialty_id") REFERENCES "public"."specialty"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "syllabus" ADD CONSTRAINT "syllabus_course_offering_id_course_offering_id_fk" FOREIGN KEY ("course_offering_id") REFERENCES "public"."course_offering"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "teacher" ADD CONSTRAINT "teacher_user_id_app_user_id_fk" FOREIGN KEY ("user_id") REFERENCES "public"."app_user"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
CREATE UNIQUE INDEX "uq_academic_period_single_active" ON "academic_period" USING btree ("is_active") WHERE "academic_period"."is_active" = TRUE;--> statement-breakpoint
CREATE INDEX "idx_advising_rsvp_session" ON "advising_rsvp" USING btree ("advising_session_id");--> statement-breakpoint
CREATE INDEX "idx_alert_student" ON "alert" USING btree ("student_id");--> statement-breakpoint
CREATE INDEX "idx_assessment_syllabus" ON "assessment" USING btree ("syllabus_id");--> statement-breakpoint
CREATE UNIQUE INDEX "uq_course_advising_session_course" ON "course_advising_session" USING btree ("course_offering_id","teacher_id","day_of_week","start_time") WHERE "course_advising_session"."section_id" IS NULL AND "course_advising_session"."kind" = 'recurring';--> statement-breakpoint
CREATE UNIQUE INDEX "uq_course_advising_session_section" ON "course_advising_session" USING btree ("section_id","teacher_id","day_of_week","start_time") WHERE "course_advising_session"."section_id" IS NOT NULL AND "course_advising_session"."kind" = 'recurring';--> statement-breakpoint
CREATE UNIQUE INDEX "uq_course_advising_session_extra" ON "course_advising_session" USING btree ("section_id","teacher_id","session_date","start_time") WHERE "course_advising_session"."kind" = 'extra';--> statement-breakpoint
CREATE INDEX "idx_course_advising_session_course_offering" ON "course_advising_session" USING btree ("course_offering_id");--> statement-breakpoint
CREATE INDEX "idx_course_offering_period" ON "course_offering" USING btree ("academic_period_id");--> statement-breakpoint
CREATE UNIQUE INDEX "uq_course_prerequisite_course" ON "course_prerequisite" USING btree ("curriculum_course_id","prerequisite_curriculum_course_id") WHERE "course_prerequisite"."prerequisite_curriculum_course_id" IS NOT NULL;--> statement-breakpoint
CREATE UNIQUE INDEX "uq_course_prerequisite_completed_cycle" ON "course_prerequisite" USING btree ("curriculum_course_id","prerequisite_type","required_cycle") WHERE "course_prerequisite"."required_cycle" IS NOT NULL;--> statement-breakpoint
CREATE INDEX "idx_course_prerequisite_curriculum_course" ON "course_prerequisite" USING btree ("curriculum_course_id");--> statement-breakpoint
CREATE INDEX "idx_curriculum_course_curriculum" ON "curriculum_course" USING btree ("curriculum_id");--> statement-breakpoint
CREATE INDEX "idx_enrollment_student" ON "enrollment" USING btree ("student_id");--> statement-breakpoint
CREATE INDEX "idx_password_reset_token_user" ON "password_reset_token" USING btree ("user_id");--> statement-breakpoint
CREATE INDEX "idx_schedule_session_section" ON "schedule_session" USING btree ("section_id");--> statement-breakpoint
CREATE INDEX "idx_section_course_offering" ON "section" USING btree ("course_offering_id");--> statement-breakpoint
CREATE UNIQUE INDEX "uq_section_jp" ON "section" USING btree ("jp_id") WHERE "section"."jp_id" IS NOT NULL;--> statement-breakpoint
CREATE UNIQUE INDEX "uq_active_section_representative_position" ON "section_representative" USING btree ("section_id","position") WHERE "section_representative"."is_active" = TRUE;--> statement-breakpoint
CREATE INDEX "idx_student_user_id" ON "student" USING btree ("user_id");--> statement-breakpoint
CREATE INDEX "idx_student_curriculum_id" ON "student" USING btree ("curriculum_id");--> statement-breakpoint
CREATE INDEX "idx_student_course_progress_student" ON "student_course_progress" USING btree ("student_id");--> statement-breakpoint
CREATE INDEX "idx_student_course_progress_curriculum_course" ON "student_course_progress" USING btree ("curriculum_course_id");--> statement-breakpoint
CREATE INDEX "idx_student_curriculum_simulation_student" ON "student_curriculum_simulation" USING btree ("student_id");--> statement-breakpoint
CREATE INDEX "idx_student_score_enrollment" ON "student_score" USING btree ("enrollment_id");--> statement-breakpoint
CREATE INDEX "idx_student_specialty_student" ON "student_specialty" USING btree ("student_id");--> statement-breakpoint
CREATE UNIQUE INDEX "uq_student_specialty_active_primary" ON "student_specialty" USING btree ("student_id") WHERE "student_specialty"."selection_type" = 'primary' AND "student_specialty"."is_active" = TRUE;