CREATE TYPE "public"."social_platform" AS ENUM('linkedin', 'instagram', 'github', 'x', 'website', 'other');--> statement-breakpoint
CREATE TABLE "user_social_link" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "user_social_link_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"user_id" integer NOT NULL,
	"platform" "social_platform" NOT NULL,
	"url" varchar(255) NOT NULL,
	"label" varchar(80),
	CONSTRAINT "uq_user_social_link_platform" UNIQUE("user_id","platform")
);
--> statement-breakpoint
ALTER TABLE "app_user" ADD COLUMN "networking_opt_in" boolean DEFAULT false NOT NULL;--> statement-breakpoint
ALTER TABLE "user_social_link" ADD CONSTRAINT "user_social_link_user_id_app_user_id_fk" FOREIGN KEY ("user_id") REFERENCES "public"."app_user"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
CREATE INDEX "idx_user_social_link_user" ON "user_social_link" USING btree ("user_id");