CREATE TABLE "simulated_grades" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "simulated_grades_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"enrollment_id" integer NOT NULL,
	"assessment_id" integer NOT NULL,
	"value" numeric(5, 2) NOT NULL,
	"updated_at" timestamp with time zone DEFAULT now() NOT NULL,
	CONSTRAINT "uq_simulated_grade" UNIQUE("enrollment_id","assessment_id"),
	CONSTRAINT "chk_simulated_grade_value" CHECK ("simulated_grades"."value" BETWEEN 0 AND 20)
);
--> statement-breakpoint
ALTER TABLE "simulated_grades" ADD CONSTRAINT "simulated_grades_enrollment_id_enrollment_id_fk" FOREIGN KEY ("enrollment_id") REFERENCES "public"."enrollment"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "simulated_grades" ADD CONSTRAINT "simulated_grades_assessment_id_assessment_id_fk" FOREIGN KEY ("assessment_id") REFERENCES "public"."assessment"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
CREATE INDEX "idx_simulated_grade_enrollment" ON "simulated_grades" USING btree ("enrollment_id");