-- Migración 0004 — HU18: rol docente, asesorías extra, JP y RSVP
-- Aditiva salvo el re-scope de dos índices únicos existentes (DROP+CREATE de
-- metadato, sin pérdida de datos). Aplicar en TRANSACCIÓN, con backup previo,
-- ANTES de mergear/desplegar el código de HU18 (runbook MIGRATIONS.md).
--
-- Idempotente donde es posible (IF NOT EXISTS / IF EXISTS). Los ADD CONSTRAINT
-- no admiten IF NOT EXISTS en PG 18, así que van con guardas DO $$ ... $$.

--> statement-breakpoint
-- 1. Vincular teacher a una cuenta (login docente). Nullable + único.
ALTER TABLE teacher ADD COLUMN IF NOT EXISTS user_id integer;
--> statement-breakpoint
DO $$ BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'teacher_user_id_unique') THEN
    ALTER TABLE teacher ADD CONSTRAINT teacher_user_id_unique UNIQUE (user_id);
  END IF;
END $$;
--> statement-breakpoint
DO $$ BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'teacher_user_id_app_user_id_fk') THEN
    ALTER TABLE teacher ADD CONSTRAINT teacher_user_id_app_user_id_fk
      FOREIGN KEY (user_id) REFERENCES app_user(id);
  END IF;
END $$;
--> statement-breakpoint

-- 2. Jefe de práctica de la sección (0 o 1). El rol Profesor/JP se deriva de la
--    columna que referencia al teacher, no de un enum en la persona.
ALTER TABLE section ADD COLUMN IF NOT EXISTS jp_id integer;
--> statement-breakpoint
DO $$ BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'section_jp_id_teacher_id_fk') THEN
    ALTER TABLE section ADD CONSTRAINT section_jp_id_teacher_id_fk
      FOREIGN KEY (jp_id) REFERENCES teacher(id);
  END IF;
END $$;
--> statement-breakpoint
DO $$ BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'chk_section_jp_not_teacher') THEN
    ALTER TABLE section ADD CONSTRAINT chk_section_jp_not_teacher
      CHECK (jp_id IS NULL OR jp_id <> teacher_id);
  END IF;
END $$;
--> statement-breakpoint
-- Un JP pertenece a una sola sección (índice único parcial: ignora NULLs).
CREATE UNIQUE INDEX IF NOT EXISTS uq_section_jp ON section (jp_id) WHERE jp_id IS NOT NULL;
--> statement-breakpoint

-- 3. Enum de tipo de asesoría (recurrente/extra).
DO $$ BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'advising_kind') THEN
    CREATE TYPE advising_kind AS ENUM ('recurring', 'extra');
  END IF;
END $$;
--> statement-breakpoint

-- 4. Columnas de asesoría extra. kind con default 'recurring' → las filas
--    existentes quedan correctamente marcadas como recurrentes.
ALTER TABLE course_advising_session ADD COLUMN IF NOT EXISTS kind advising_kind NOT NULL DEFAULT 'recurring';
--> statement-breakpoint
ALTER TABLE course_advising_session ADD COLUMN IF NOT EXISTS session_date date;
--> statement-breakpoint
ALTER TABLE course_advising_session ADD COLUMN IF NOT EXISTS capacity integer;
--> statement-breakpoint
DO $$ BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'chk_course_advising_extra_date') THEN
    ALTER TABLE course_advising_session ADD CONSTRAINT chk_course_advising_extra_date
      CHECK (kind <> 'extra' OR session_date IS NOT NULL);
  END IF;
END $$;
--> statement-breakpoint
DO $$ BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'chk_course_advising_capacity') THEN
    ALTER TABLE course_advising_session ADD CONSTRAINT chk_course_advising_capacity
      CHECK (capacity IS NULL OR capacity > 0);
  END IF;
END $$;
--> statement-breakpoint

-- 5. Re-scope de los únicos de "día+hora" a solo recurrentes (permite dos
--    extras el mismo día de semana a la misma hora en fechas distintas) y
--    unicidad propia de extras por fecha. DROP+CREATE de metadato (sin datos).
DROP INDEX IF EXISTS uq_course_advising_session_course;
--> statement-breakpoint
CREATE UNIQUE INDEX IF NOT EXISTS uq_course_advising_session_course
  ON course_advising_session (course_offering_id, teacher_id, day_of_week, start_time)
  WHERE section_id IS NULL AND kind = 'recurring';
--> statement-breakpoint
DROP INDEX IF EXISTS uq_course_advising_session_section;
--> statement-breakpoint
CREATE UNIQUE INDEX IF NOT EXISTS uq_course_advising_session_section
  ON course_advising_session (section_id, teacher_id, day_of_week, start_time)
  WHERE section_id IS NOT NULL AND kind = 'recurring';
--> statement-breakpoint
CREATE UNIQUE INDEX IF NOT EXISTS uq_course_advising_session_extra
  ON course_advising_session (section_id, teacher_id, session_date, start_time)
  WHERE kind = 'extra';
--> statement-breakpoint

-- 6. RSVP de estudiantes (conteo/lista de asistentes; escritura en HU17).
CREATE TABLE IF NOT EXISTS advising_rsvp (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  advising_session_id integer NOT NULL REFERENCES course_advising_session(id),
  student_id integer NOT NULL REFERENCES student(id),
  created_at timestamptz NOT NULL DEFAULT now(),
  CONSTRAINT uq_advising_rsvp UNIQUE (advising_session_id, student_id)
);
--> statement-breakpoint
CREATE INDEX IF NOT EXISTS idx_advising_rsvp_session ON advising_rsvp (advising_session_id);
